allowBuilds:
  unrs-resolver: true
ignoredBuiltDependencies:
  - unrs-resolver
minimumReleaseAgeExclude:
  - js-yaml@3.15.0 || 3.15.1
  - '@orcabus/platform-cdk-constructs@1.9.3'
overrides:
  browserslist@<=4.28.6: ^4.28.7
